---
- name: Play for Frontend server deployment
  hosts: FRONTEND
  become: yes
  tags: frontend
  roles:
    - name: frontend

- name: Play for mongodb server deployment
  hosts: MONGODB
  become: yes
  tags: mongodb
  roles:
    - name: mongodb

- name: Play for Catalogue server deployment
  hosts: CATALOGUE
  become: yes
  tags: catalogue
  roles:
    - name: catalogue

- name: Play for REDIS server deployment
  hosts: REDIS
  become: yes
  tags: redis
  roles:
    - name: redis

- name: Play for USER server deployment
  hosts: USER
  become: yes
  tags: user
  roles:
    - name: user

- name: Play for CART server deployment
  hosts: CART
  become: yes
  tags: cart
  roles:
    - name: cart

- name: Play for MySQL server deployment
  hosts: MYSQL
  become: yes
  tags: mysql
  roles:
    - name: mysql

- name: Play for SHIPPING server deployment
  hosts: SHIPPING
  become: yes
  tags: shipping
  roles:
    - name: shipping

- name: Play for RabbitMQ server deployment
  hosts: RABBITMQ
  become: yes
  tags: rabbitmq
  roles:
    - name: rabbitmq

- name: Play for PAYMENT server deployment
  hosts: PAYMENT
  become: yes
  tags: payment
  roles:
    - name: payment