- name: RoboShop Frontend Setup
  hosts: FRONTEND
  become: yes
  tags: frontend
  roles:
    - name: frontend

- name: RoboShop MONGODB Setup
  hosts: MONGODB
  become: yes
  tags: mongodb
  roles:
    - name: mongodb

- name: RoboShop CATALOGUE Setup
  hosts: CATALOGUE
  become: yes
  tags: catalogue
  roles:
    - name: catalogue
