---
- name: Simple Play 1
  hosts: all
  become: yes
  tasks:
    - hostname:
        name: testweb01
    - name: Add epel-release repo
        yum:
          name: epel-release
          state: present

      - name: Install nginx
        yum:
          name: nginx
          state: present

      - name: Insert Index Page
        template:
          src: index.html
          dest: /usr/share/nginx/html/index.html

      - name: Start NGiNX
        service:
          name: nginx
          state: started

     - name: Unarchive a file that needs to be downloaded (added in 2.0)
       ansible.builtin.unarchive:
         src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
         dest: /usr/share/nginx/html