- name: setting Hostname RABBITMQ
  hostname:
    name: rabbitmq

- name: Installing Erlang is a dependency for RabbitMQ
  yum:
    name: https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm
    state: present

- name: YUM repositories for RabbitMQ.
  shell:
    name: https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install RabbitMQ
  yum:
    name: rabbitmq-server
    state: present

- name: Start RabbitMQ service
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Create App User in RoboShop
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    tags: roboshop administrator
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present