- name: Installing nodejs
  yum:
    name: [ "nodejs", "make", "gcc-c++" ]
    state: present

- name: Add roboshop user
  ansible.builtin.user:
    name: roboshop
    comment: roboshop

- name: Downloading nodejs Archieves from GITHUB
  include_role:
     name: common
     tasks_from: download

- name: Copy nodes files in roboshop home directory
  copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
    owner: roboshop
    group: roboshop
    mode: '0755'

- name: Install dependents using npm
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}/
    state: latest
  become_user: roboshop

- name: Copy systemd comnfiguration
  copy:
    src: systemd.conf
    dest: /etc/systemd/system/{{COMPONENT}}.service
    owner: root
    group: root
    mode: '0755'

- name: Restart {{COMPONENT}} Service
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes