---
- name: monngodb play 1
  hosts: all
  become: yes
  tasks:
  - hostname:
      name: mongodb

  - name: Create a MongoDB repo
    copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Add epel-release repo
    yum:
      name: mongodb-org
      state: present

  - name: Replace localhost config to everyone
    replace:
      dest: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Restart service mongodb, in all cases
    ansible.builtin.service:
      name: mongod
      enabled: yes
      state: restarted

  - name: Unarchive a mongodb files downloaded
    ansible.builtin.unarchive:
        src: https://github.com/roboshop-devops-project/mongodb/archive/main.zip
        dest: /tmp
        remote_src: yes

